builds:
  -
    binary: bucketeer-find-code-refs
    id: bucketeer-find-code-refs
    main: ./cmd/bucketeer-find-code-refs/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - "amd64"
      - "arm64"

    ignore:
      - goos: darwin
        goarch: "386"
  -
    binary: bucketeer-find-code-refs-github-action
    id: bucketeer-find-code-refs-github-action
    main: ./build/package/github-actions/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "amd64"
  -
    binary: bucketeer-find-code-refs-bitbucket-pipeline
    id: bucketeer-find-code-refs-bitbucket-pipeline
    main: ./build/package/bitbucket-pipelines/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "amd64"

archives:
  -
    id: bucketeer-find-code-refs
    builds:
    - bucketeer-find-code-refs

nfpms:
  -
    id: bucketeer-find-code-refs
    file_name_template: >-
      {{- .ProjectName -}}_
      {{- .Version -}}.
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end -}}

    homepage: https://bucketeer.io/
    maintainer: Bucketeer <bucketeer@cyberagent.co.jp>
    description: Job for finding and sending feature flag code references to Bucketeer
    license: Apache 2.0
    vendor: Bucketeer

    formats:
    - deb
    - rpm

brews:
  -
    ids:
    - bucketeer-find-code-refs

    name: bucketeer-find-code-refs

    description: Job for finding and sending feature flag code references to Bucketeer

    homepage: "https://bucketeer.io"

    repository:
      owner: bucketeer
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

    folder: Formula

    url_template: "https://github.com/bucketeer-io/code-refs/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    install: |
      bin.install "bucketeer-find-code-refs"

    commit_author:
      name: BucketeerReleaseBot
      email: bucketeer@cyberagent.co.jp

release:
  disable: true # this disables releasing *to GitHub*; it will still push to Docker
  # (we want Releaser to be responsible for doing all the GitHub release manipulations)

dockers:
  -
    image_templates:
    - "bucketeer/bucketeer-find-code-refs:latest"
    - "bucketeer/bucketeer-find-code-refs:{{ .Version }}"

    dockerfile: Dockerfile

  -
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    ids:
    - bucketeer-find-code-refs-github-action

    image_templates:
    - "bucketeer/bucketeer-find-code-refs-github-action:latest"
    - "bucketeer/bucketeer-find-code-refs-github-action:{{ .Version }}"

    dockerfile: Dockerfile.github
  -
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64

    image_templates:
    - "bucketeer/bucketeer-find-code-refs-bitbucket-pipeline:latest"
    - "bucketeer/bucketeer-find-code-refs-bitbucket-pipeline:{{ .Version }}"

    ids:
    - bucketeer-find-code-refs-bitbucket-pipeline

    dockerfile: Dockerfile.bitbucket
