FROM alpine:3.19

RUN apk update
RUN apk add --no-cache git

COPY bucketeer-find-code-refs-bitbucket-pipeline /bucketeer-find-code-refs-bitbucket-pipeline

ENTRYPOINT ["/bucketeer-find-code-refs-bitbucket-pipeline"]
