FROM alpine:3.19

RUN apk update
RUN apk add --no-cache git

COPY bucketeer-find-code-refs-github-action /bucketeer-find-code-refs-github-action

LABEL com.github.actions.name="Bucketeer Code References"
LABEL com.github.actions.description="Find references to feature flags in your code."
LABEL com.github.actions.icon="toggle-right"
LABEL com.github.actions.color="gray-dark"
LABEL homepage="https://bucketeer.io"

ENTRYPOINT ["/bucketeer-find-code-refs-github-action"]
