# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BucketeerFindCodeRefs < Formula
  desc "Bucketeer Code References. This tool will find and send feature flag code references to Bucketeer's backend."
  homepage "https://bucketeer.io"
  version "0.0.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bucketeer-io/code-refs/releases/download/v0.0.1/code-refs_0.0.1_darwin_amd64.tar.gz"
      sha256 "017b1d581b91fce49e1a5b2539a895ac642f257cbe2ca06c2b02841be3955e57"

      def install
        bin.install "bucketeer-find-code-refs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bucketeer-io/code-refs/releases/download/v0.0.1/code-refs_0.0.1_darwin_arm64.tar.gz"
      sha256 "4fd9b6342d0607f8ec8eb78f8112b96820a8a41424600ae43d6bb25a93b01ca1"

      def install
        bin.install "bucketeer-find-code-refs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bucketeer-io/code-refs/releases/download/v0.0.1/code-refs_0.0.1_linux_amd64.tar.gz"
        sha256 "6774e0720a6a424a3cbe7500d733ce10a740aa8e4690947448cc580865d15a6a"

        def install
          bin.install "bucketeer-find-code-refs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bucketeer-io/code-refs/releases/download/v0.0.1/code-refs_0.0.1_linux_arm64.tar.gz"
        sha256 "0c94aa5d62b873843b92010ad55dcfa0739e08004b85e87f5485d231757039bd"

        def install
          bin.install "bucketeer-find-code-refs"
        end
      end
    end
  end
end
