# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BucketeerFindCodeRefs < Formula
  desc "Bucketeer Code References. This tool will find and send feature flag code references to Bucketeer's backend."
  homepage "https://bucketeer.io"
  version "0.0.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bucketeer-io/code-refs/releases/download/v0.0.1/code-refs_0.0.1_darwin_amd64.tar.gz"
      sha256 "40463dc0b9e685a9a68b3bb08e27ef974948ac8391337739d0dd96cd2aaafc4a"

      def install
        bin.install "bucketeer-find-code-refs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bucketeer-io/code-refs/releases/download/v0.0.1/code-refs_0.0.1_darwin_arm64.tar.gz"
      sha256 "1f7e3298fdca743bc759a30e4bde907e8c5eb01146ff25ce6d93e5dd7b1b940e"

      def install
        bin.install "bucketeer-find-code-refs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bucketeer-io/code-refs/releases/download/v0.0.1/code-refs_0.0.1_linux_amd64.tar.gz"
        sha256 "acce7294df4e19364a1a004e8f7a065e1d03f2105e0ed6f2d2002030e4090228"

        def install
          bin.install "bucketeer-find-code-refs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bucketeer-io/code-refs/releases/download/v0.0.1/code-refs_0.0.1_linux_arm64.tar.gz"
        sha256 "e000eddf05e4c7bba1375f5994730ef0f5e9dec7be24d2732fbf2cd68bb47ab5"

        def install
          bin.install "bucketeer-find-code-refs"
        end
      end
    end
  end
end
